version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8086:80"
    volumes:
      - ./docker-config/nginx-pica.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/pica
    links:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker-config/Dockerfile-php
    volumes:
      - ./:/var/www/pica
    links:
      - database
      - elasticsearch
  database:
    image: mysql
    ports:
      - "33060:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/fonoteka.sql:/docker-entrypoint-initdb.d/00_pica.sql
    environment:
      MYSQL_ROOT_PASSWORD: huehuehuehue
      MYSQL_DATABASE: fonoteka_pica
      MYSQL_USER: FONOTEKA
      MYSQL_PASSWORD: huehuehue
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  elasticsearch:
    build:
      context: .
      dockerfile: ./docker-config/Dockerfile-elasticsearch

