fos_elastica:
  clients:
    default: { host: %elasticsearch_host%, port: %elasticsearch_port% }

  indexes:
    picapica:

      settings:
        index:
          analysis:

            filter:
              edgeNGram_filter:
                type: edgeNGram
                min_gram: 2
                max_gram: 20
                side: front

            analyzer:

              edge_NGram_analyzer:
                type: custom
                tokenizer: edge_ngram_tokenizer
                filter:
                   - lowercase
                   - asciifolding

              edge_NGram_analyzer_fid:
                type: custom
                tokenizer: edge_ngram_tokenizer_fid
                filter:
                   - lowercase
                   - asciifolding

              whitespace_analyzer:
                type: custom
                tokenizer: whitespace
                filter:
                  - lowercase
                  - asciifolding

              keyword_analyzer:
                type: custom
                tokenizer: keyword
                filter:
                  - lowercase
                  - asciifolding

            tokenizer:
              edge_ngram_tokenizer:
                  type: edgeNGram
                  min_gram: 2
                  max_gram: 20
                  token_chars:
                    - letter
                    - digit

              edge_ngram_tokenizer_fid:
                  type: edgeNGram
                  min_gram: 2
                  max_gram: 20

      types:

        artist:
          _all:
            analyzer: edge_NGram_analyzer
            #search_analyzer: whitespace_analyzer

          mappings:
            id:
              type: integer
              include_in_all: false

            name:
              type: string
              analyzer: whitespace_analyzer
              #search_analyzer: whitespace_analyzer
              fields:
                autocomplete:
                  type: string
                  analyzer: edge_NGram_analyzer
                  #search_analyzer: whitespace_analyzer

            autocompleteName:
              type: string
              include_in_all: false
              index: not_analyzed
              fields:
                autocomplete:
                  type: string
                  analyzer: edge_NGram_analyzer
                  #search_analyzer: whitespace_analyzer

          persistence:
            driver: orm
            model: RadioStudent\AppBundle\Entity\Artist
            provider: ~
            listener: ~
            finder: ~
            model_to_elastica_transformer:
              service: search.transformer.model.artist



        album:
          _all:
            analyzer: edge_NGram_analyzer
            #search_analyzer: whitespace_analyzer

          mappings:
            id:
              type: integer
              include_in_all: false

            fid:
              type: string
              include_in_all: false
              index: not_analyzed
              fields:
                autocomplete:
                  type: string
                  analyzer: edge_NGram_analyzer_fid
                  #search_analyzer: keyword_analyzer
                numeric:
                  type: string
                  analyzer: whitespace
                  #search_analyzer: whitespace

            name:
              type: string
              analyzer: whitespace_analyzer
              #search_analyzer: whitespace_analyzer
              fields:
                autocomplete:
                  type: string
                  analyzer: edge_NGram_analyzer
                  #search_analyzer: whitespace_analyzer

          persistence:
            driver: orm
            model: RadioStudent\AppBundle\Entity\Album
            provider: ~
            listener: ~
            finder: ~



        track:
          _all:
            analyzer: edge_NGram_analyzer
            #search_analyzer: whitespace_analyzer

          mappings:
            id:
              type: integer
              include_in_all: false

            track_fid:
              property_path: fid
              type: string
              include_in_all: true
              analyzer: edge_NGram_analyzer
              #search_analyzer: whitespace_analyzer
              fields:
                autocomplete:
                  type: string
                  analyzer: edge_NGram_analyzer_fid
                  #search_analyzer: keyword_analyzer
                numeric:
                  type: string
                  analyzer: whitespace
                  #search_analyzer: whitespace
                order:
                  type: string
                  analyzer: keyword_analyzer

            trackNum:
              include_in_all: false
              index: not_analyzed
              fields:
                raw:
                  type: string
                  index: not_analyzed
                order:
                  type: string
                  analyzer: keyword_analyzer

            track_name:
              include_in_all: true
              property_path: name
              analyzer: edge_NGram_analyzer
              #search_analyzer: whitespace_analyzer
              fields:
                autocomplete:
                  type: string
                  analyzer: edge_NGram_analyzer
                  #search_analyzer: whitespace_analyzer
                order:
                  type: string
                  analyzer: keyword_analyzer

            duration:
              type: integer
              include_in_all: false
              fields:
                order:
                  type: integer

            date:
              type: date
              include_in_all: false
              format: date_time_no_millis
              fields:
                order:
                  type: date

            artist:
              type: object
              properties:
#                id:
#                  type: integer
#                  include_in_all: false
#                  index_name: track_artist_id
                id:
                  property_path: allRelatedArtistIds
                  include_in_all: false
                track_artist_name:
                  include_in_all: true
                  property_path: name
                  analyzer: edge_NGram_analyzer
                  #search_analyzer: whitespace_analyzer
                  fields:
                    order:
                      type: string
                      analyzer: keyword_analyzer

            album:
              type: object
              properties:
                track_album_id:
                  property_path: id
                  type: integer
                  include_in_all: false
                track_album_fid:
                  property_path: fid
                  include_in_all: false
                  index: not_analyzed
                track_album_name:
                  property_path: name
                  include_in_all: true
                  analyzer: edge_NGram_analyzer
                  #search_analyzer: whitespace_analyzer
                  fields:
                    order:
                      type: string
                      analyzer: keyword_analyzer


          persistence:
            driver: orm
            model: RadioStudent\AppBundle\Entity\Track
            provider:
              batch_size: 1000
            listener: ~
            finder: ~
