fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

radio_student_app:
    resource: "@RadioStudentAppBundle/Controller/"
    type:     annotation
    prefix:   /

API_artists:
    type: rest
    resource: @RadioStudentAppBundle/Controller/API/ArtistController.php

API_albums:
    type: rest
    resource: @RadioStudentAppBundle/Controller/API/AlbumController.php

API_tracks:
    type: rest
    resource: @RadioStudentAppBundle/Controller/API/TrackController.php

API_tracklists:
    type: rest
    resource: @RadioStudentAppBundle/Controller/API/TracklistController.php

API_autocomplete:
    type: rest
    resource: @RadioStudentAppBundle/Controller/API/AutoCompleteController.php

#radio_student_API:
#  type: rest
#  prefix: /api
#  resource: "routing_api.yml"
