security:
    erase_credentials: false

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Radiostudent\AppBundle\Entity\User: plaintext
        AcmeBundle\Acme\User\LdapUser: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_EDITOR:      ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]

    firewalls:
        main:
            pattern: ^/
            form_login:
                #provider: fos_userbundle
                provider: chain_provider
                #provider: fr3d_ldapbundle
                csrf_token_generator: security.csrf.token_manager
                #always_use_default_target_path: true
                #default_target_path: /profile

            remember_me:
                secret: '%secret%'
                lifetime: 2592000
                path: /

            fr3d_ldap: ~

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/.*$, role: ROLE_USER }
