"use strict"

require "angular"
    .module "picapicaApp"
        .service "SearchFilter",   require "./search-filter"
        .service "SortableColumn", require "./sortable-column"
        .service "SelectedTracks", require "./selected-tracks"
        .factory "Track",          require "./resource/track"
        .factory "TrackList",      require "./resource/track-list"
        .factory "Suggestion",     require "./resource/suggestion"
        .factory "Term",           require "./resource/term"
