require 'angular'
    .module 'picapicaApp'
        .controller 'TrackSearchController', require './track-search'
        .controller 'PlaylistController',    require './playlist'
        .controller 'AlbumEditorController', require './album-editor'
