imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: elastica.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    assets:
        version: "v0.4.5"
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: ~
        cookie_lifetime: 0
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
      default_connection: db1
      connections:
        db1:
          driver:   "%database_driver%"
          host:     "%database_host%"
          port:     "%database_port%"
          dbname:   "%database_name%"
          user:     "%database_user%"
          password: "%database_password%"
          charset:  UTF8
        db2:
          driver:   "%database_driver%"
          host:     "%database_host%"
          port:     "%database_port%"
#          dbname:   fonoteka_old
          user:     "%database_user%"
          password: "%database_password%"
          charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_rest:
    routing_loader:
        default_format: json

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: RadioStudent\AppBundle\Entity\User
    from_email:
      address: "%mailer_address%"
      sender_name: "%mailer_sender_name%"

fr3d_ldap:
    driver:
        host: bartoldo.radiostudent.local
        bindRequiresDn: false
        username: null
        password: null
        useSsl: false
        useStartTls: false
    user:
        baseDn: "ou=Users,dc=radiostudent,dc=si"
        filter: "(objectclass=inetOrgPerson)"
        attributes:
            - { ldap_attr: uid, user_method: setUsername }
            - { ldap_attr: email, user_method: setEmail }
